#!/bin/bash

DAEMON=denon_http

. /etc/rc.conf
. /etc/rc.d/functions

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

PID=$(get_pid $DAEMON)

case "$1" in
  start)
    stat_busy "Starting $DAEMON"
    if [[ -z $DENON_IP ]]; then
      stat_fail ; exit 1
    fi
    if [[ -z $LOCAL_PORT ]]; then
      stat_fail ; exit 1
    fi
    ARGS="localhost -L 0.0.0.0:$LOCAL_PORT:$DENON_IP:80 -N -f"
    [ -z "$PID" ] && ssh $ARGS &> /dev/null
    if [ $? = 0 ]; then
      add_daemon $DAEMON
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping $DAEMON"
    [ -n "$PID" ] && kill $PID &>/dev/null
    if [ $? = 0 ]; then
      rm_daemon $DAEMON
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  status)
    stat_busy "Checking $DAEMON";
    ck_status $daemon_name
    ;;
    
  *)
    echo "usage: $0 {start|stop|restart|status}"
esac

exit 0